services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    image: mushroom_bet_api-prod
    container_name: mushroom_bet_api
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: postgres://postgres:postgres@db:5432/mushroom
    ports:
      - '3001:3001'
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: mushroom_bet_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mushroom
    volumes:
      - pgdata_prod:/var/lib/postgresql/data

volumes:
  pgdata_prod:
