version: '3.9'

services:
  api:
    # Build the “dev” stage for hot-reloading
    build:
      context: .
      target: dev
    image: mushroom_bet_api_dev:latest
    container_name: mushroom_bet_api
    command: >
      sh -c "
        bun prisma migrate dev &&          # auto-apply dev migrations
        bun --hot src/main.ts              # start NestJS in watch-mode
      "
    volumes:
      - .:/app:delegated # live-mount source code
      - node_deps:/app/node_modules # keep container’s node_modules
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: postgres://postgres:postgres@db:5432/mushroom
    ports:
      - '3001:3001'
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3001/health']
      interval: 30s
      timeout: 5s
      retries: 5

  db:
    image: postgres:16
    container_name: mushroom_bet_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mushroom
    ports:
      - '5432:5432'
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      retries: 5

volumes:
  pgdata_dev:
  node_deps:
