services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: mushroom-bet-api-dev
    container_name: mushroom_bet_api
    command: bun --hot src/main.ts
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mushroom
    ports:
      - '3001:3001'
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: mushroom_bet_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mushroom
    ports:
      - '5432:5432'
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

volumes:
  pgdata_dev:
