import { Character, Prisma, PrismaClient } from '@prisma/client';

const prisma: PrismaClient = new PrismaClient();

async function main() {
  const skinData: Prisma.SkinCreateInput[] = [
    { name: 'DEFAULT', character: Character.MARIO },
    { name: 'TOURING', character: Character.MARIO },
    { name: 'PRO_RACER', character: Character.MARIO },
    { name: 'MECHANIC', character: Character.MARIO },
    { name: 'DUNE_RIDER', character: Character.MARIO },
    { name: 'COWBOY', character: Character.MARIO },
    { name: 'SIGHTSEEING', character: Character.MARIO },
    { name: 'AVIATOR', character: Character.MARIO },
    { name: 'HAPPI', character: Character.MARIO },
    { name: 'ALL_TERRAIN', character: Character.MARIO },
    { name: 'DEFAULT', character: Character.PEACH },
    { name: 'TOURING', character: Character.PEACH },
    { name: 'PRO_RACER', character: Character.PEACH },
    { name: 'FARMER', character: Character.PEACH },
    { name: 'SIGHTSEEING', character: Character.PEACH },
    { name: 'AVIATOR', character: Character.PEACH },
    { name: 'YUKATA', character: Character.PEACH },
    { name: 'AERO', character: Character.PEACH },
    { name: 'VACATION', character: Character.PEACH },
    { name: 'DEFAULT', character: Character.YOSHI },
    { name: 'TOURING', character: Character.YOSHI },
    { name: 'GREEN', character: Character.YOSHI },
    { name: 'RED', character: Character.YOSHI },
    { name: 'BLUE', character: Character.YOSHI },
    { name: 'YELLOW', character: Character.YOSHI },
    { name: 'PINK', character: Character.YOSHI },
    { name: 'BLACK', character: Character.YOSHI },
    { name: 'WHITE', character: Character.YOSHI },
    { name: 'DEFAULT', character: Character.LUIGI },
    { name: 'TOURING', character: Character.LUIGI },
    { name: 'PRO_RACER', character: Character.LUIGI },
    { name: 'OASIS', character: Character.LUIGI },
    { name: 'FARMER', character: Character.LUIGI },
    { name: 'HAPPI', character: Character.LUIGI },
    { name: 'ALL_TERRAIN', character: Character.LUIGI },
    { name: 'GONDOLIER', character: Character.LUIGI },
    { name: 'DEFAULT', character: Character.SHY_GUY },
    { name: 'BLACK', character: Character.SHY_GUY },
    { name: 'BLUE', character: Character.SHY_GUY },
    { name: 'GREEN', character: Character.SHY_GUY },
    { name: 'YELLOW', character: Character.SHY_GUY },
    { name: 'WHITE', character: Character.SHY_GUY },
    { name: 'ORANGE', character: Character.SHY_GUY },
    { name: 'PINK', character: Character.SHY_GUY },
    { name: 'DEFAULT', character: Character.DAISY },
    { name: 'TOURING', character: Character.DAISY },
    { name: 'PRO_RACER', character: Character.DAISY },
    { name: 'OASIS', character: Character.DAISY },
    { name: 'SWIMWEAR', character: Character.DAISY },
    { name: 'AERO', character: Character.DAISY },
    { name: 'VACATION', character: Character.DAISY },
    { name: 'DEFAULT', character: Character.ROSALINA },
    { name: 'TOURING', character: Character.ROSALINA },
    { name: 'PRO_RACER', character: Character.ROSALINA },
    { name: 'AERO', character: Character.ROSALINA },
    { name: 'VACATION', character: Character.ROSALINA },
    { name: 'DEFAULT', character: Character.TOAD },
    { name: 'CHEF', character: Character.TOAD },
    { name: 'AVIATOR', character: Character.TOAD },
    { name: 'HAPPI', character: Character.TOAD },
    { name: 'SKIER', character: Character.TOAD },
    { name: 'DEFAULT', character: Character.BABY_ROSALINA },
    { name: 'TOURING', character: Character.BABY_ROSALINA },
    { name: 'PRO_RACER', character: Character.BABY_ROSALINA },
    { name: 'SAILOR', character: Character.BABY_ROSALINA },
    { name: 'EXPLORER', character: Character.BABY_ROSALINA },
    { name: 'DEFAULT', character: Character.WARIO },
    { name: 'WARRIOR', character: Character.WARIO },
    { name: 'GOLD', character: Character.WARIO },
    { name: 'COWBOY', character: Character.WARIO },
    { name: 'OFFROAD', character: Character.WARIO },
    { name: 'DEFAULT', character: Character.TOADETTE },
    { name: 'CHEF', character: Character.TOADETTE },
    { name: 'WARRIOR', character: Character.TOADETTE },
    { name: 'TOURING', character: Character.TOADETTE },
    { name: 'DEFAULT', character: Character.BABY_MARIO },
    { name: 'RACER', character: Character.BABY_MARIO },
    { name: 'SAILOR', character: Character.BABY_MARIO },
    { name: 'SUNNY', character: Character.BABY_MARIO },
    { name: 'DEFAULT', character: Character.BABY_LUIGI },
    { name: 'RACER', character: Character.BABY_LUIGI },
    { name: 'SAILOR', character: Character.BABY_LUIGI },
    { name: 'FARMER', character: Character.BABY_LUIGI },
    { name: 'DEFAULT', character: Character.BABY_PEACH },
    { name: 'VACATION', character: Character.BABY_PEACH },
    { name: 'SPRING', character: Character.BABY_PEACH },
    { name: 'PILOT', character: Character.BABY_PEACH },
    { name: 'DEFAULT', character: Character.BABY_DAISY },
    { name: 'VACATION', character: Character.BABY_DAISY },
    { name: 'SPRING', character: Character.BABY_DAISY },
    { name: 'PILOT', character: Character.BABY_DAISY },
    { name: 'DEFAULT', character: Character.BOWSER },
    { name: 'ARMOR', character: Character.BOWSER },
    { name: 'ROYAL', character: Character.BOWSER },
    { name: 'FURY', character: Character.BOWSER },
    { name: 'DEFAULT', character: Character.DONKEY_KONG },
    { name: 'JUNGLE', character: Character.DONKEY_KONG },
    { name: 'WINTER', character: Character.DONKEY_KONG },
    { name: 'RACER', character: Character.DONKEY_KONG },
    { name: 'DEFAULT', character: Character.WALUIGI },
    { name: 'ATHLETE', character: Character.WALUIGI },
    { name: 'RACER', character: Character.WALUIGI },
    { name: 'SAND', character: Character.WALUIGI },
    { name: 'DEFAULT', character: Character.GOOMBA },
    { name: 'DEFAULT', character: Character.KOOPA_TROOPA },
    { name: 'DEFAULT', character: Character.PIRANHA_PLANT },
    { name: 'DEFAULT', character: Character.HAMMER_BRO },
    { name: 'DEFAULT', character: Character.CHARGIN_CHUCK },
    { name: 'DEFAULT', character: Character.MONTY_MOLE },
    { name: 'DEFAULT', character: Character.POKEY },
    { name: 'DEFAULT', character: Character.PARA_BIDDYBUD },
    { name: 'DEFAULT', character: Character.SPIKE },
    { name: 'DEFAULT', character: Character.WIGGLER },
    { name: 'DEFAULT', character: Character.NABBIT },
    { name: 'DEFAULT', character: Character.PIANTA },
    { name: 'DEFAULT', character: Character.MOO_MOO },
    { name: 'DEFAULT', character: Character.PENGUIN },
    { name: 'DEFAULT', character: Character.SIDESTEPPER },
    { name: 'DEFAULT', character: Character.SNOWMAN },
    { name: 'DEFAULT', character: Character.STINGBY },
    { name: 'DEFAULT', character: Character.CATAQUACK },
    { name: 'DEFAULT', character: Character.CHEEP_CHEEP },
    { name: 'DEFAULT', character: Character.FISH_BONE },
    { name: 'DEFAULT', character: Character.DOLPHIN },
    { name: 'DEFAULT', character: Character.ROCKY_WRENCH },
    { name: 'DEFAULT', character: Character.LAKITU },
    { name: 'DEFAULT', character: Character.DRY_BONES },
  ];

  await prisma.skin.createMany({
    data: skinData,
    skipDuplicates: true,
  });
}

void main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => {
    return prisma.$disconnect();
  });
